# Generated by Django 2.2.1 on 2019-06-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pill_detection', '0004_auto_20190602_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated',
        ),
    ]
