# Generated by Django 2.2.1 on 2019-06-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_detection', '0005_auto_20190602_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='pillinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('corporation', models.CharField(max_length=100)),
                ('effect', models.CharField(max_length=1000)),
                ('dosage', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
