# Generated by Django 2.2.1 on 2019-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='no_image.jpg', null=True, upload_to='%d'),
        ),
    ]
